version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID}
        - USER=${USER}
    container_name: laravel_server_nginx_container
    volumes:
      - ./app_volume:/var/www
    working_dir: /var/www
    networks:
      - laravel-network
    ports:
      - 8008:80
    depends_on:
      - php
      - database
    links:
      - database

  #apache:
  #  build:
  #    context: .
  #    dockerfile: apache.dockerfile
  #  container_name: laravel_server_apache_container
  #  restart: always
  #  volumes:
  #    - ./app_volume:/var/www
  #  working_dir: /var/www
  #  networks:
  #    - laravel-network
  #  ports:
  #    - 8008:80
  #  depends_on:
  #    - php
  #    - database
  #  links:
  #    - database

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: laravel_php_container
    volumes:
      - ./app_volume:/var/www
    networks:
      - laravel-network

  database:
    image: mysql:8.0.27
    container_name: laravel_database_container
    restart: always
    volumes:
      - ./db_volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'laravel_db'
      MYSQL_USER: 'laravel_db_user'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_ROOT_HOST: '%'
    networks:
      - laravel-network
    ports:
      - 3366:3306
    expose:
      - '3306'

  #database:
  #  image: mariadb:10.5
  #  container_name: laravel_database_container
  #  restart: always
  #  volumes:
  #      - ./db_volume:/var/lib/mysql
  #  environment:
  #      MYSQL_DATABASE: 'laravel_db'
  #      MYSQL_USER: 'laravel_db_user'
  #      MYSQL_PASSWORD: 'secret'
  #      MYSQL_ROOT_PASSWORD: 'secret'
  #      MYSQL_ROOT_HOST: '%'
  #  networks:
  #      - laravel-network
  #  ports: 
  #      - "3366:3306"
  #  expose:
  #      - "3306"
  #  command: --default-authentication-plugin=mysql_native_password
    

  composer:
    image: composer:latest
    container_name: laravel_composer_container
    volumes:
      - ./app_volume:/var/www
    working_dir: /var/www
    networks:
      - laravel-network

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: laravel_artisan_container
    volumes:
      - ./app_volume:/var/www
    working_dir: /var/www
    entrypoint: ['php', 'artisan']
    networks:
      - laravel-network

  npm:
    image: node:20-alpine
    container_name: laravel_npm_container
    volumes:
      - ./app_volume:/var/www
    working_dir: /var/www
    entrypoint: ['npm']
    networks:
      - laravel-network

  mailpit:
      image: axllent/mailpit
      container_name: laravel_mailpit_container
      ports:
        - "1025:1025"
        - "8025:8025"
      networks:
        - laravel-network

networks:
  laravel-network: