version: '3'

services:

  web_server:
    image: webkul/apache-php:1.5.1
    container_name: ceela_store_apache2
    restart: always
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    environment:
      USER_ID: 1003
    networks:
      - ceela-network
    ports:
      - '8888:80'
    expose:
      - '80'
    depends_on:
      - database_server
    links:
      - database_server

  database_server:
    image: mysql:5.7
    container_name: ceela_store_mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'ceela_store_db'
      MYSQL_USER: 'ceela_store_db_user'
      MYSQL_PASSWORD: '12345'
      MYSQL_ROOT_PASSWORD: '12345'
      MYSQL_ROOT_HOST: '%'
    networks:
      - ceela-network
    ports:
      - '3333:3306'
    expose:
      - '3306'
    volumes:
      - ./dbvolume:/var/lib/mysql

volumes:
  dbvolume:
  app:

networks:
  ceela-network:

