version: '3'

services:

  web_server:
    image: webkul/apache-php:1.5.1
    container_name: bagisto_web_server_container
    restart: always
    volumes:
      - ./app_volume:/var/www/html
    working_dir: /var/www/html
    environment:
      USER_ID: 1003
    networks:
      - bagisto-network
    ports:
      - '8888:80'
    expose:
      - '80'
    depends_on:
      - database_server
    links:
      - database_server

  database_server:
    image: mysql:5.7
    container_name: bagisto_database_container
    restart: always
    environment:
      MYSQL_DATABASE: 'bagisto_db'
      MYSQL_USER: 'bagisto_db_user'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_ROOT_HOST: '%'
    networks:
      - bagisto-network
    ports:
      - '33:3306'
    expose:
      - '3306'
    volumes:
      - ./db_volume:/var/lib/mysql

volumes:
  app_volume:
  db_volume:

networks:
  bagisto-network:

