version: "3.1"

services:

    web_server:
        image: webdevops/php-apache:7.4-alpine
        container_name: web_server_php74
        restart: always
        volumes:
            - ./app_volume:/var/www/
        working_dir: /var/www/
        networks:
            - lamp74-network
        ports: 
            - "8008:80"
        expose:
            - "80"
        depends_on:
            - database_server
        links:
            - database_server
        
    database_server:
        image: mariadb:10.5
        container_name: database_server
        restart: always
        environment:
            MYSQL_DATABASE: 'lamp_database'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'secret'
            MYSQL_ROOT_PASSWORD: 'secret'
            MYSQL_ROOT_HOST: '%'
        networks:
            - lamp74-network
        ports: 
            - "3366:3306"
        expose:
            - "3306"
        command: --default-authentication-plugin=mysql_native_password
        
        volumes:
            - ./db_volume:/var/lib/mysql
        
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin_server
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        networks:
            - lamp74-network
        ports:
            - 8080:80
        links: 
            - database_server:db
        
volumes:
    app_volume:
    db_volume:

networks:
    lamp74-network:
